# Generated by Django 6.0.3 on 2026-03-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('document', models.FileField(upload_to='print_orders/')),
                ('print_type', models.CharField(choices=[('text', 'Text Document'), ('photo', 'Photo Print')], max_length=10)),
                ('copies', models.IntegerField(default=1)),
                ('pages', models.IntegerField()),
                ('color_type', models.CharField(choices=[('bw', 'Black & White'), ('color', 'Color')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('ready', 'Ready'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
