# Generated by Django 6.0.3 on 2026-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printorder',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup at Shop'), ('delivery', 'Home Delivery')], default='pickup', max_length=10),
        ),
        migrations.AddField(
            model_name='printorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('momo', 'Mobile Money'), ('card', 'Card Payment')], max_length=10),
        ),
        migrations.AddField(
            model_name='printorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='printorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
