# Generated by Django 6.0.3 on 2026-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_printorder_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_bw_price', models.DecimalField(decimal_places=2, default=0.5, max_digits=6, verbose_name='Text B/W Price per Page')),
                ('text_color_price', models.DecimalField(decimal_places=2, default=1.5, max_digits=6, verbose_name='Text Color Price per Page')),
                ('photo_bw_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Photo B/W Price per Page')),
                ('photo_color_price', models.DecimalField(decimal_places=2, default=2.0, max_digits=6, verbose_name='Photo Color Price per Page')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Home Delivery Fee')),
            ],
            options={
                'verbose_name_plural': 'Print Pricing',
            },
        ),
    ]
